### ISSUE TITLE
Master is broken: AttributeError: 'Sphinx' object has no attribute 'domains'

### ISSUE THREAD

**Issue by a3kov** [repoze/repoze.sphinx.autointerface#10]
```
Running Sphinx v1.6.2

Exception occurred:
  File "/home/crea/workspaces/python/repoze.sphinx.autointerface/repoze/sphinx/autointerface.py", line 104, in setup
    class InterfacePythonDomain(app.domains['py']):
AttributeError: 'Sphinx' object has no attribute 'domains'
```

**Comment by clokep** [comment]
The `domains` property seems to have been removed in sphinx-doc/sphinx#3656 and I think this line needs to be replaced with the [`add_directive_to_domain` method](http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_directive_to_domain)?

**Comment by dataflake** [comment]
This has been solved a long time ago, closing.
