### ISSUE TITLE
0.8: test suite requires sphinx.ext.autodoc module

### ISSUE THREAD

**Issue by kloczek** [repoze/repoze.sphinx.autointerface#15]
Issue is that I cannot find sphinx.ext.autodoc on pypi :/

**Comment by jamadden** [comment]
It's a core part of Sphinx, there should be nothing to install. [Here it is in the sphinx repository](https://github.com/sphinx-doc/sphinx/tree/4.x/sphinx/ext/autodoc).

**Comment by kloczek** [comment]
Yep 😄 Closing.
