### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mithrandi** [repoze/repoze.sphinx.autointerface#5]
Could we get a new release? Not much has changed since the last release, but it's been quite a while, and I'd like to get my hands on a05288882d257d18121e3d10c0f8c67dc60e0693.

**Comment by tseaver** [comment]
Done:

  https://pypi.python.org/pypi/repoze.sphinx.autointerface/0.8

**Comment by mithrandi** [comment]
Wow, thanks for the speedy response! :fireworks: :tada:
