### ISSUE TITLE
:members: is not really respected?

### ISSUE THREAD

**Issue by jamadden** [repoze/repoze.sphinx.autointerface#7]
At least not with modern Sphinx (1.4). 

This stems from a conversation @jimfulton and I were having over in [zodbdocs](https://github.com/zopefoundation/zodbdocs/pull/24#discussion_r77993725). When I tried to test `:members:` in a local RelStorage checkout, it appeared to be completely ignored and everything in the interface was documented. 

I could have missed something and there's no test cases here to check on so I'll have to try a smaller example at some point.

Jim's [version of the interface documenter class](https://bitbucket.org/j1m/sphinxautointerface/src/050eb3a69fca737fbc264b2dff9984ab704279b6/j1m/sphinxautointerface.py?at=default&fileviewer=file-view-default#sphinxautointerface.py-95) is *much* simpler, maybe because it supports newer Sphinx versions only?

**Comment by jimfulton** [comment]
First, "mine" is just a fork with small fixes. :) Second, it's probably simpler because it subclasses bits from autodoc, especially autoclass. (It looks like autodoc made some specific accommodations for it.)

**Comment by jamadden** [comment]
[`rezpoze.sphix.autointerface.InterfaceDocumenter`](https://github.com/repoze/repoze.sphinx.autointerface/blob/master/repoze/sphinx/autointerface.py#L25) subclasses the same `sphinx.ext.autodoc.ClassDocumenter` as your fork does.

**Comment by jamadden** [comment]
It turns out that `autointerface` respects `:members:` just fine, *as long as you don't have them turned on by default*. The same thing goes for `autoclass`.

If you have members enabled by default in conf.py:
```
autodoc_default_flags = ['members']
```

then the [AutoDirective](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc.py#L1602) will override whatever you put for `:members:` in any particular directive with `None`---which turns into `ALL`.

The solution is to put `:no-members:`, and then `:members: my,list,of,members`, e.g.:

```
.. autointerface:: relstorage.adapters.interfaces.IRelStorageAdapter
     :no-members:
     :members: connmanager
```

In the process of figuring this out, I have the start of a test suite for this package, so I'll open a PR for that.
